<a href="https://colab.research.google.com/github/inwoo01/asdf/blob/main/inwoo240313.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: print("Hello, World!")

print("Hello, World!")

# integer
x = 3
print ("정수: %01d, %02d, %03d, %04d, %05d"
        %(x,x,x,x,x))

# float
x = 256.123
print ("실수: %.0f, %.1f, %.2f"
        %(x,x,x))

#string
x = "Hello, World!"
print ("문자열: [%s]" % (x))

Hello, World!
정수: 3, 03, 003, 0003, 00003
실수: 256, 256.1, 256.12
문자열: [Hello, World!]


In [ ]:
contents = ["Regression", "Classification", "SYM", "Clustering", "Dimension reduction",
            "NN","CNN", "AE", "GAN", "RNN"]
for con in contents:
  if con in ["Regression", "Classification", "SYM", "Clustering", "Dimension reduction"]:
    print ("%s 은(는) 기계학습 내용입니다." %con)
  elif con in ["CNN"]:
    print ("%s 은(는) convolutional neural network 입니다." %con)
  else:
    print ("%s 은(는) 심층학습 내용입니다." %con)

for (i,con) in enumerate(contents):
  print ("[%d/%d]: %s" %(i, len(contents),con))

Regression 은(는) 기계학습 내용입니다.
Classification 은(는) 기계학습 내용입니다.
SYM 은(는) 기계학습 내용입니다.
Clustering 은(는) 기계학습 내용입니다.
Dimension reduction 은(는) 기계학습 내용입니다.
NN 은(는) 심층학습 내용입니다.
CNN 은(는) convolutional neural network 입니다.
AE 은(는) 심층학습 내용입니다.
GAN 은(는) 심층학습 내용입니다.
RNN 은(는) 심층학습 내용입니다.
[0/10]: Regression
[1/10]: Classification
[2/10]: SYM
[3/10]: Clustering
[4/10]: Dimension reduction
[5/10]: NN
[6/10]: CNN
[7/10]: AE
[8/10]: GAN
[9/10]: RNN


In [ ]:
def sum(a,b):
  return a+b

x=10.0
y=20.0
print ("%.1f + %.1f = %.1f" %(x,y,sum(x,y)))

10.0 + 20.0 = 30.0


In [ ]:
a=[]
b=[1,2,3]
c=["Hello", ",","world"]
d=[1,2,3,"x","y","z"]
x=[]
print (x)

x.append('a')
print (x)

x.append(123)
print (x)

x.append(["a","b"])
print (x)


[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


In [ ]:
dic = dict()
dic["name"] = "Daesik"
dic["town"] = "Yongin city"
dic["job"] = "Assistant professor"
print (dic)

{'name': 'Daesik', 'town': 'Yongin city', 'job': 'Assistant professor'}


In [ ]:
class Student:
  # 생성자
   def __init__(self,name):
       self.name = name
  # 메써드
   def study(self, hard=False):
     if hard:
      print ("%s 학생은 열심히 공부합니다." %self.name)
     else:
      print ("%s 학생은 공부합니다." %self.name)
s = Student('Daesik')
s.study()
s.study(hard=True)


Daesik 학생은 공부합니다.
Daesik 학생은 열심히 공부합니다.


In [20]:
import numpy as np

def print_val(x):
  print ("Type:", type(x))
  print ("Shape:", x.shape)
  print ("값:\n",x)
  print ("")

x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

a = np.random.random((4,4))
print_val(a)

a = np.random.randn(4,4)
print_val(a)

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)

b= a[:2, 1:3] #행 0~1 , 열 1~2
print_val(b)

# 행렬의 n번째 행 얻기

row1 = a[1,:]
print_val(row1)

m1 = np.array([[1,2],[3,4]], dtype=np.float64)
m2 = np.array([[5,6],[7,8]], dtype=np.float64)

#행렬의 합
print_val(m1+m2)
print_val(np.add(m1,m2))

#행렬의 차
print_val(m1-m2)
print_val(np.subtract(m1,m2))

#행렬의 곱
print_val(m1*m2)
print_val(np.multiply(m1,m2))

#행렬의 나누기
print_val(m1/m2)
print_val(np.divide(m1,m2))

#행렬의 제곱근
print_val(np.sqrt(m1))



m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
v1 = np.array([9,10])
v2 = np.array([11,12])

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

#벡터-벡터 연산

print_val(v1.dot(v2))
print_val(np.dot(v1,v2))

#벡터-행렬 연산

print_val(m1.dot(v1))
print_val(np.dot(m1,v1))

#행렬-행렬 연산

print_val(m1.dot(m2))
print_val(np.dot(m1,m2))

#전치 행렬(transpose)

print_val(m1)
print_val(m1.T)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.85754034 0.49417398 0.23774592 0.66581478]
 [0.71685604 0.19145774 0.01505943 0.76507053]
 [0.4929678  0.34767154 0.59634752 0.66785245]
 [0.78081193 0.7485266  0.78437209 0.14576091]]

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[ 0.00208966  0.71809845  1.75148545 -0.07920939]
 [-1.90837698 -0.02205875  0.70340292  1.04988093]
 [ 0.83637462 -1.3998706  -0.75399063  1.10643414]
 [ 0.74720055  0.43070766  0.60873136  1.03814678]]

Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[2 3]
 [6 7]]

Type: <class 'numpy.ndarray'>
Shape: (4,)
값:
 [5 6 7 8]

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]

Type: <class 'numpy.ndarray'>
Shape: (